language: python
python: 3.6

arch:
  - amd64
  - ppc64le

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOX_ENV=py36-111
  - TOX_ENV=py36-21
  - TOX_ENV=py36-22
  - TOX_ENV=py36-master
  - TOX_ENV=docs
  - TOX_ENV=flake8

matrix:
  allow_failures:
    - env: TOX_ENV=py36-master
  fast_finish: true

install:
  - pip install tox --cache-dir $HOME/.pip-cache

script:
  - tox -e $TOX_ENV
