language: python
python: 3.5

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py27-110
  - TOX_ENV=py27-111
  - TOX_ENV=py27-master
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py34-110
  - TOX_ENV=py34-111
  - TOX_ENV=py34-master
  - TOX_ENV=py35-18
  - TOX_ENV=py35-19
  - TOX_ENV=py35-110
  - TOX_ENV=py35-111
  - TOX_ENV=py35-master
  - TOX_ENV=docs
  - TOX_ENV=flake8

matrix:
  allow_failures:
    - env: TOX_ENV=py27-master
    - env: TOX_ENV=py34-master
    - env: TOX_ENV=py35-master
  fast_finish: true

install:
  - pip install tox --cache-dir $HOME/.pip-cache

script:
  - tox -e $TOX_ENV
