name: Test

on: [push, pull_request]

jobs:
  build:
    name: build (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        django-version: ['4.0', '4.1', '4.2', '5.0', '5.1']
        include:
          # Tox configuration for documentation environment
          - python-version: '3.9'
            django-version: 'docs'
          # Tox configuration for QA environment
          - python-version: '3.9'
            django-version: 'qa'
          # Django main
          - python-version: '3.10'
            django-version: 'main'
            experimental: true
          - python-version: '3.11'
            django-version: 'main'
            experimental: true
          - python-version: '3.12'
            django-version: 'main'
            experimental: true
          # - python-version: '3.13'
          #   django-version: 'main'
          #   experimental: true
        exclude:
          # Exclude Django 4.0 for Python 3.7 as it is not supported
          - python-version: '3.11'
            django-version: '4.0'
          - python-version: '3.12'
            django-version: '4.0'
          # - python-version: '3.13'
          #   django-version: '4.0'
          - python-version: '3.12'
            django-version: '4.1'
          # - python-version: '3.13'
          #   django-version: '4.1'
          - python-version: '3.9'
            django-version: '5.0'
          # - python-version: '3.13'
          #   django-version: '5.0'
          - python-version: '3.9'
            django-version: '5.1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM for Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pdm sync -d -G dev

    - name: Run pytest
      run: |
        pdm run -v pytest --cov-report term-missing --cov-report xml --cov=docopt
      env:
        DJANGO: ${{ matrix.django-version }}

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        name: Python ${{ matrix.python-version }}

    - name: Build wheels and sdist
      run: |
        pdm build

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        # These are pure-python, so we don't need to worry about platform
        name: wheels-python-${{ matrix.python-version }}-django-${{ matrix.django-version }}
        # name: Python ${{ matrix.python-version }}
        path: |
          dist/*.whl
          dist/*.tar.gz

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: dist

      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/django-recurrence/upload

